apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - web.yaml
  - ssh.yaml
  - rdp.yaml
  - smb.yaml
  - vnc.yaml
  - cloudflared/secret.yaml
  - cloudflared/deployment.yaml
