apiVersion: apps/v1
kind: Deployment
metadata:
  name: smb
  namespace: cloudflare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smb
  template:
    metadata:
      labels:
        app: smb
    spec:
      containers:
      - name: samba
        image: dockurr/samba:latest
        ports:
        - containerPort: 445
        env:
        - name: USER
          value: "cloudflare"
        - name: PASS
          value: "cloudflare"
        volumeMounts:
        - name: smb-data
          mountPath: /share
      volumes:
      - name: smb-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: smb
  namespace: cloudflare
spec:
  type: ClusterIP
  clusterIP: 10.10.22.45
  selector:
    app: smb
  ports:
  - protocol: TCP
    port: 445
    targetPort: 445
