apiVersion: apps/v1
kind: Deployment
metadata:
  name: vnc
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vnc
  template:
    metadata:
      labels:
        app: vnc
    spec:
      containers:
      - name: vnc
        image: kasmweb/desktop:1.14.0-rolling-weekly
        ports:
        - containerPort: 6901
          name: vnc
        env:
        - name: VNC_PW
          value: "demo"
        securityContext:
          runAsUser: 0
        readinessProbe:
          httpGet:
            path: /
            port: 6901
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 6901
          initialDelaySeconds: 60
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: vnc
  namespace: demo
spec:
  type: ClusterIP
  clusterIP: 10.43.0.59
  selector:
    app: vnc
  ports:
  - protocol: TCP
    port: 6901
    targetPort: 6901
    name: vnc
